import type { CSSProperties } from "react";

/**
 * The IMUN seal.
 *
 * The institutional mark is monochrome navy line art, so it is shipped in two
 * tones: a white rendition for the navy header/footer/hero, and a navy
 * rendition for light surfaces. Both are transparent PNGs generated by
 * `npm run process:logo`.
 */
export function BrandLogo({
  className = "",
  style,
  priority = false,
  tone = "onDark",
}: {
  className?: string;
  style?: CSSProperties;
  priority?: boolean;
  tone?: "onDark" | "onLight";
}) {
  const src =
    tone === "onLight" ? "/assets/brand/iemun-seal.png" : "/assets/brand/iemun-logo.png";

  return (
    // eslint-disable-next-line @next/next/no-img-element
    <img
      src={src}
      alt="IMUN — Indian MUN seal"
      width={600}
      height={600}
      className={className}
      style={style}
      loading={priority ? "eager" : "lazy"}
      decoding="async"
    />
  );
}
